# Generated by Django 3.0.1 on 2020-01-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='latitude',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='longitude',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='latitude',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='longitude',
            field=models.CharField(max_length=12),
        ),
    ]
